sonar.projectKey=cm-acr-cataloganalysisservice
sonar.projectName=cm-acr-cataloganalysisservice
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.language=java
sonar.java.binaries=.
sonar.qualitygate.ignoreSmallChanges=false
sonar.coverage.exclusions=**/src/test/**/*.*

