server.port=7200
server.servlet.context-path=/acr

spring.r2dbc.url=r2dbc:postgresql://${PG_URL}/${PG_DB}
spring.r2dbc.username=${PG_USER}
spring.r2dbc.password=${PG_PWD}

spring.r2dbc.pool.initial-size=100
spring.r2dbc.pool.max-size=500
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.validation-query=SELECT 1
spring.r2dbc.pool.validation-interval=30000
spring.r2dbc.pool.time-between-eviction-runs-millis=60000

xsb.report.file.delimiter=\\~\\|\\~

#logging.level.io.r2dbc.postgresql.QUERY=DEBUG
#logging.level.io.r2dbc.postgresql.PARAM=DEBUG

# This next property (spring.mvc.async.request-timeout) is needed otherwise  any long running transaction
# makes the web client timeout
#spring.mvc.async.request-timeout = -1