spring.r2dbc.url=r2dbc:postgresql://${PG_URL}/${PG_DB}
spring.r2dbc.username=${PG_USER}
spring.r2dbc.password=${PG_PWD}

spring.r2dbc.pool.initial-size=100
spring.r2dbc.pool.max-size=500
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.validation-query=SELECT 1
#spring.r2dbc.pool.validation-interval=30000
#spring.r2dbc.pool.time-between-eviction-runs-millis=60000
