package gov.gsa.acr.cataloganalysis.service;

import gov.gsa.acr.cataloganalysis.error.ErrorHandler;
import gov.gsa.acr.cataloganalysis.model.XsbData;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.*;


@SpringBootTest
@Slf4j
@ContextConfiguration(classes = {XsbDataParser.class, ErrorHandler.class})
@TestPropertySource(locations="classpath:application-test.properties")
class XsbDataParserTest {

    @Autowired
    XsbDataParser xsbDataParser;
    @Autowired
    private ErrorHandler errorHandler;

    List<String> taaCountryCodes = Arrays.asList("AF", "AG", "AM", "AO", "AT", "AU", "AW", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BQ", "BS", "BT", "BZ", "CA", "CD", "CF", "CH", "CL", "CO", "CR", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "EE", "ER", "ES", "ET", "FI", "FR", "GB", "GD", "GM", "GN", "GQ", "GR", "GS", "GT", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "IE", "IL", "IS", "IT", "JM", "JP", "KH", "KI", "KM", "KN", "KR", "LA", "LC", "LI", "LR", "LS", "LT", "LU", "LV", "MA", "MD", "ME", "MG", "ML", "MR", "MS", "MT", "MW", "MX", "MZ", "NE", "NI", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PL", "PT", "RO", "RW", "SB", "SE", "SG", "SI", "SK", "SL", "SN", "SO", "SS", "ST", "SV", "SX", "TD", "TG", "TP", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "VC", "VG", "VU", "WS", "YE", "ZM", "XX");

    private final String validHeader = "contractNumber~|~modificationNumber~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice";
    private final String extendedValidHeader = "contractNumber~|~modificationNumber~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice~|~mdfGroupId~|~extraHeader1~|~extraHeader2~|~extraHeader3";

    @BeforeEach
    void setUp() {
       errorHandler.init(validHeader);
    }

    @Test
    void init() {
        assertEquals("\\~\\|\\~", xsbDataParser.getDelimRegex());
        assertEquals("~|~", xsbDataParser.getDelimString());
        assertEquals(validHeader, xsbDataParser.getHeaderString());
    }

    @Test
    void testValidateHeader() {
        assertTrue(xsbDataParser.validateHeader(validHeader));

        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice"};
        assertArrayEquals(expectedHeader, xsbDataParser.getHeader());
    }

    @Test
    void testValidateExtendedHeader() {
        assertTrue(xsbDataParser.validateHeader(extendedValidHeader));

        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice", "mdfGroupId", "extraHeader1","extraHeader2","extraHeader3"};
        assertArrayEquals(expectedHeader, xsbDataParser.getExtendedHeaderArray());
    }

    @Test
    void testValidateExtendedHeaderExtraField() {
        assertTrue(xsbDataParser.validateHeader(extendedValidHeader+"~|~extraHeader"));

        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice", "mdfGroupId", "extraHeader1","extraHeader2","extraHeader3" };
        assertArrayEquals(expectedHeader, xsbDataParser.getExtendedHeaderArray());
    }

    @Test
    void testNullHeader() {
        boolean b = xsbDataParser.validateHeader(null);
        assertFalse(b);
    }

    @Test
    void testBlankHeader() {
        boolean b = xsbDataParser.validateHeader("");
        assertFalse(b);
    }

    @Test
    void testInvalidHeaderExtraFieldPrepended() {
        String invalidHeader = "extra~|~contractNumber~|~modificationNumber~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice";
        assertFalse(xsbDataParser.validateHeader(invalidHeader));
    }

    @Test
    void testInvalidHeaderExtraFieldsInTheMiddle() {
        String invalidHeader = "contractNumber~|~extra1~|~modificationNumber~|~extra2~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice";
        assertFalse(xsbDataParser.validateHeader(invalidHeader));
    }


    @Test
    void testInvalidHeaderExtraFieldsAppended() {
        String invalidHeader = "contractNumber~|~modificationNumber~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice~|~extra1~|~extra2~|~extra3";
        assertTrue(xsbDataParser.validateHeader(invalidHeader));
    }


    @Test
    void testInvalidHeaderMissingField() {
        String invalidHeader = "modificationNumber~|~vendorName~|~vendorPartNumber~|~vendorDescription~|~bpaNumber~|~solicitationNumber~|~dunsNumber~|~sin~|~sinInference~|~sinsMatch~|~manufacturerName~|~manufacturerPartNumber~|~quantityOfUnit~|~quantityPerUnit~|~unitOfIssue~|~standardizedManufacturerName~|~standardizedManufacturerPartNumber~|~standardizedUnitOfIssue~|~fsc~|~nsn~|~unspsc~|~globalPackagingIdentifier~|~standardizedGlobalPackagingIdentifier~|~productName~|~productType~|~standardizedProductName~|~standardizedProductDescription~|~uniqueItemIdentifier~|~standardizedPackageQuantity~|~hits~|~selfHits~|~abilityOneItem~|~bioPreferred~|~comprehensiveProcurementGuidelineCompliant~|~significantNewAlternativesPolicyApproved~|~federalEnergyManagementProgramEnergyEfficientItem~|~waterSense~|~saferChoice~|~energyStar~|~epeat~|~primeItem~|~epaPrimaryMetalsFree~|~lowVoc~|~ets~|~deliveryFob~|~uniqueItemIdentifierScore~|~finalPrice~|~lowPriceTarget~|~midPriceTarget~|~highPriceTarget~|~catalogMinPrice~|~catalogAvgPrice~|~catalogMedianPrice~|~catalogMaxPrice~|~catalogPriceStandardDeviation~|~transactionMinPrice~|~transactionAvgPrice~|~transactionMedianPrice~|~transactionMaxPrice~|~catalogMinPriceSupplier~|~catalogMedianPriceSupplier~|~catalogMaxPriceSupplier~|~catalogMinPriceDelta~|~catalogAvgPriceDelta~|~catalogMedianPriceDelta~|~commercialCatalogLowPriceTarget~|~commercialCatalogMidPriceTarget~|~commercialCatalogHighPriceTarget~|~commercialCatalogMinPrice~|~commercialCatalogAvgPrice~|~commercialCatalogMedianPrice~|~commercialCatalogMaxPrice~|~commercialCatalogPriceStandardDeviation~|~commercialCatalogMinPriceSupplier~|~commercialCatalogMedianPriceSupplier~|~commercialCatalogMaxPriceSupplier~|~countryOriginInference~|~demandWeightedIndexScore~|~rankCategory~|~salesLikelihood~|~catalogMinPriceSource~|~catalogMedianPriceSource~|~catalogMaxPriceSource~|~isAuthorizedVendor~|~isProhibited~|~prohibitionCondition~|~prohibitionReason~|~prohibitionComment~|~fedmallMinPrice~|~fedmallMedPrice~|~fedmallAvgPrice~|~fedmallMaxPrice~|~nasaSewpMinPrice~|~nasaSewpMedPrice~|~nasaSewpAvgPrice~|~nasaSewpMaxPrice~|~vppSupplyCategoryId~|~vppIndicator~|~itemIdentifier~|~systemOfRecord~|~annualDemandQuantity~|~standardizedSinPrevalence~|~userDefinedInput~|~countryOrigin~|~unattributedManufacturerPartNumber~|~isInvalid~|~invalidReason~|~tdrAvgPrice~|~tdrMaxPrice~|~tdrMedianPrice~|~tdrMinPrice";
        assertFalse(xsbDataParser.validateHeader(invalidHeader));
    }


    @Test
    void parseXsbDataToArray() {
        String xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        String[] expected = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","",""};
        assertArrayEquals(expected, xsbDataParser.parseXsbDataToArray(xsbData));
        //assertTrue(Arrays.equals(expected, xsbDataParser.parseXsbDataToArray(xsbData)));
    }

    @Test
    void parseInvalidXsbDataToArray() {
        String xsbData = "~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(xsbData));
    }

    @Test
    void parseInvalidXsbDataToArrayMissingFields() {
        //No contract number
        String xsbData = "~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(xsbData));
    }
    @Test
    void parseInvalidXsbDataToArrayExtraFieldPrepended() {
        String xsbData = "extra~|~extra~|~extra~|~extra~|~extra~|~47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        String[] expected = {"extra","extra","extra","extra","extra","47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","",""};
        assertArrayEquals(expected, xsbDataParser.parseXsbDataToArray(xsbData));
    }

    @Test
    void parseInvalidXsbDataToArrayExtraFieldInTheMiddle() {
        String xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~extra1~|~extra2~|~extra3~|~extra4~|~extra5~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        String[] expected = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","extra1","extra2","extra3","extra4","extra5","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","",""};
        assertArrayEquals(expected, xsbDataParser.parseXsbDataToArray(xsbData));
    }

    @Test
    void parseInvalidXsbDataToArrayExtraFieldAppended() {
        String xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~~|~extra1~|~extra2~|~extra3~|~extra4~|~extra5";
        String[] expected = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","","","extra1","extra2","extra3","extra4","extra5"};
        assertArrayEquals(expected, xsbDataParser.parseXsbDataToArray(xsbData));
    }

    @Test
    void testtest() {
        String xsbData;
        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-232Y LED Changeable Message Sign, 34\" x 71\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30062326~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30062326~|~EA~|~~|~~|~~|~~|~~|~GP-232Y LED CHANGEABLE MESSAGE SIGN~|~~|~GP-232Y LED CHANGEABLE MESSAGE SIGN~|~GP-232Y LED Changeable Message Sign, 34\" x 71\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~91580959~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~7263.48~|~7263.48~|~7626.66~|~7989.83~|~7263.48~|~7263.48~|~7263.48~|~7263.48~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 1: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 1:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-232T Advantage-S LED Portable Changeable Message Sign, 34\" x 71\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30062815~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30062815~|~EA~|~~|~~|~~|~~|~~|~GP-232T ADVANTAGE-S LED PORTABLE CHANGEA~|~~|~GP-232T ADVANTAGE-S LED PORTABLE CHANGEA~|~GP-232T Advantage-S LED Portable Changeable Message Sign, 34\" x 71\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~91580960~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~10635.32~|~10635.32~|~11167.09~|~11698.85~|~10635.32~|~10635.32~|~10635.32~|~10635.32~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~~|~\n";
            log.info("Line 2: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 2:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-465Y LED Changeable Message Sign, 48\" x 78\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30064051~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30064051~|~EA~|~~|~~|~~|~~|~~|~GP-465Y LED CHANGEABLE MESSAGE SIGN~|~~|~GP-465Y LED CHANGEABLE MESSAGE SIGN~|~GP-465Y LED Changeable Message Sign, 48\" x 78\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~91580961~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~8125.38~|~8125.38~|~8531.65~|~8937.92~|~8125.38~|~8125.38~|~8125.38~|~8125.38~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~\n";
            log.info("Line 3: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 3:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-432Y LED Changeable Message Sign, 48\" x 96\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30064347~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30064347~|~EA~|~~|~~|~~|~~|~~|~GP-432Y LED CHANGEABLE MESSAGE SIGN~|~~|~GP-432Y LED CHANGEABLE MESSAGE SIGN~|~GP-432Y LED Changeable Message Sign, 48\" x 96\" FULL matrix display, yoke-mountedassembly for vehicle installation, 20' controller and power leads, electric screw actuator for raise/lower~|~91580962~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~8976.22~|~8976.22~|~9425.03~|~9873.84~|~8976.22~|~8976.22~|~8976.22~|~8976.22~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 4: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 4:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-465T Advantage-S LED Portable Changeable Message Sign, 48\" x 78\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30064625~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30064625~|~EA~|~~|~~|~~|~~|~~|~GP-465T ADVANTAGE-S LED PORTABLE CHANGEA~|~~|~GP-465T ADVANTAGE-S LED PORTABLE CHANGEA~|~GP-465T Advantage-S LED Portable Changeable Message Sign, 48\" x 78\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~91580963~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~11486.15~|~11486.15~|~12060.46~|~12634.77~|~11486.15~|~11486.15~|~11486.15~|~11486.15~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Low~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 5: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 5:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~GP-432T Advantage-S LED Portable Changeable Message Sign, 48\" x 96\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30064710~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30064710~|~EA~|~~|~~|~~|~~|~~|~GP-432T ADVANTAGE-S LED PORTABLE CHANGEA~|~~|~GP-432T ADVANTAGE-S LED PORTABLE CHANGEA~|~GP-432T Advantage-S LED Portable Changeable Message Sign, 48\" x 96\" FULL matrixdisplay, trailer-mounted, standard power configuration (4x 6VDC batteries / 80Wsolar / AC charger / MPPT solar charge controller)~|~91580964~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~12336.97~|~12336.97~|~12953.82~|~13570.67~|~12336.97~|~12336.97~|~12336.97~|~12336.97~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 6: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 6:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~CMS-T331 LED Portable Changeable Message Sign, up to 3-line x 8-characters CHARACTER matrix display, trailer-mounted, standard power configuration (6x 6VDC batteries / 80W solar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30065211~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30065211~|~EA~|~~|~~|~~|~~|~~|~CMS-T331 LED PORTABLE CHANGEABLE MESSAGE~|~~|~CMS-T331 LED PORTABLE CHANGEABLE MESSAGE~|~CMS-T331 LED Portable Changeable Message Sign, up to 3-line x 8-characters CHARACTER matrix display, trailer-mounted, standard power configuration (6x 6VDC batteries / 80W solar / AC charger / MPPT solar charge controller)~|~91580965~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~12098.74~|~12098.74~|~12703.68~|~13308.61~|~12098.74~|~12098.74~|~12098.74~|~12098.74~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 7: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 7:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~CMS-T332 LED Portable Changeable Message Sign, up to 3-line x 12-characters LINEmatrix display, trailer-mounted, standard power configuration (6x 6VDC batteries / 80W solar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30065251~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30065251~|~EA~|~~|~~|~~|~~|~~|~CMS-T332 LED PORTABLE CHANGEABLE MESSAGE~|~~|~CMS-T332 LED PORTABLE CHANGEABLE MESSAGE~|~CMS-T332 LED Portable Changeable Message Sign, up to 3-line x 12-characters LINEmatrix display, trailer-mounted, standard power configuration (6x 6VDC batteries / 80W solar / AC charger / MPPT solar charge controller)~|~91580966~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~13145.51~|~13145.51~|~13802.79~|~14460.06~|~13145.51~|~13145.51~|~13145.51~|~13145.51~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 8: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 8:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~CMS-T333 LED Portable Changeable Message Sign, up to 4-lines x 12-characters FULL matrix display, trailer-mounted, standard power configuration (6x 6VDC Batteries / 160W solar / AC charger / MPPT solar charge controller)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS30065271~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS30065271~|~EA~|~~|~~|~~|~~|~~|~CMS-T333 LED PORTABLE CHANGEABLE MESSAGE~|~~|~CMS-T333 LED PORTABLE CHANGEABLE MESSAGE~|~CMS-T333 LED Portable Changeable Message Sign, up to 4-lines x 12-characters FULL matrix display, trailer-mounted, standard power configuration (6x 6VDC Batteries / 160W solar / AC charger / MPPT solar charge controller)~|~91580967~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~14122.93~|~14122.93~|~14829.08~|~15535.22~|~14122.93~|~14122.93~|~14122.93~|~14122.93~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 9: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 9:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~CMS-T131 DigiBrite Advantage LED motorist speed detection and feedback sign, 2-digit display of 18\" high characters, trailer-mounted, electro-hydraulic mast, 48\"x60\" R2-1 Speed Limit Sign, standard power configuration (4x 6VDC batteries / AC charger/ 80W solar)~|~~|~~|~612764845~|~339950~|~339950~|~true~|~AMERICAN SIGNAL COMPANY~|~AMS60065226~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~AMS60065226~|~EA~|~~|~~|~~|~~|~~|~CMS-T131 DIGIBRITE ADVANTAGE LED MOTORIS~|~~|~CMS-T131 DIGIBRITE ADVANTAGE LED MOTORIS~|~CMS-T131 DigiBrite Advantage LED motorist speed detection and feedback sign, 2-digit display of 18\" high characters, trailer-mounted, electro-hydraulic mast, 48\"x60\" R2-1 Speed Limit Sign, standard power configuration (4x 6VDC batteries / AC charger/ 80W solar)~|~91580968~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~7178.84~|~7178.84~|~7537.78~|~7896.72~|~7178.84~|~7178.84~|~7178.84~|~7178.84~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 10: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 10:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Warranty, Extended 1 Year 2 yrs total, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30065079~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30065079~|~EA~|~~|~~|~~|~~|~~|~WARRANTY, EXTENDED 1 YEAR 2 YRS TOTAL, A~|~~|~WARRANTY, EXTENDED 1 YEAR 2 YRS TOTAL, A~|~Warranty, Extended 1 Year 2 yrs total, available for all models~|~82089160~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~765.74~|~765.74~|~851.76~|~937.77~|~765.74~|~765.74~|~765.74~|~765.74~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 11: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 11:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Warranty, Extended 2 Years 3 years total, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30065080~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30065080~|~EA~|~~|~~|~~|~~|~~|~WARRANTY, EXTENDED 2 YEARS 3 YEARS TOTAL~|~~|~WARRANTY, EXTENDED 2 YEARS 3 YEARS TOTAL~|~Warranty, Extended 2 Years 3 years total, available for all models~|~82089161~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~1389.82~|~1389.82~|~1522.03~|~1654.24~|~1389.82~|~1389.82~|~1389.82~|~1389.82~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 12: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 12:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~AimStar Tilt/Rotate Solar Assembly (up to two Solar Panels) available for all 33x / Advantage / ChromaView 2~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30065098-3~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT300650983~|~EA~|~~|~~|~~|~~|~~|~AIMSTAR TILT/ROTATE SOLAR ASSEMBLY (UP T~|~~|~AIMSTAR TILT/ROTATE SOLAR ASSEMBLY (UP T~|~AimStar Tilt/Rotate Solar Assembly (up to two Solar Panels) available for all 33x / Advantage / ChromaView 2~|~91580953~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~1435.77~|~1435.77~|~1571.53~|~1707.28~|~1435.77~|~1435.77~|~1435.77~|~1435.77~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 13: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 13:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~WiFi local wireless control, available for select models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30065395-1~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT300653951~|~EA~|~~|~~|~~|~~|~~|~WIFI LOCAL WIRELESS CONTROL, AVAILABLE F~|~~|~WIFI LOCAL WIRELESS CONTROL, AVAILABLE F~|~WiFi local wireless control, available for select models~|~91580954~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~287.15~|~287.15~|~326.64~|~366.13~|~287.15~|~287.15~|~287.15~|~287.15~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 14: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 14:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~AimStar Tilt/Rotate Solar Assembly, (up to two solar panels) available for all Advantage-S / ChromaView 1~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30065526~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30065526~|~EA~|~~|~~|~~|~~|~~|~AIMSTAR TILT/ROTATE SOLAR ASSEMBLY, (UP~|~~|~AIMSTAR TILT/ROTATE SOLAR ASSEMBLY, (UP~|~AimStar Tilt/Rotate Solar Assembly, (up to two solar panels) available for all Advantage-S / ChromaView 1~|~91580955~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~815.52~|~815.52~|~904.99~|~994.46~|~815.52~|~815.52~|~815.52~|~815.52~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 15: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 15:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Radar, Overspeed Detection K-Band speed detection, available for all 33x / Advantage / Advantage-S / ChromaView~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125076~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125076~|~EA~|~~|~~|~~|~~|~~|~RADAR, OVERSPEED DETECTION K-BAND SPEED~|~~|~RADAR, OVERSPEED DETECTION K-BAND SPEED ~|~Radar, Overspeed Detection K-Band speed detection, available for all 33x / Advantage / Advantage-S / ChromaView~|~91580956~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~861.46~|~861.46~|~953.89~|~1046.31~|~861.46~|~861.46~|~861.46~|~861.46~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 16: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 16:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Cellular Option (GPS Not Activated) available for all 33x / Advantage / Advantage-S / Advantage-HC / ChromaView / BroadView~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125310~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125310~|~EA~|~~|~~|~~|~~|~~|~CELLULAR OPTION (GPS NOT ACTIVATED) AVAI~|~~|~CELLULAR OPTION (GPS NOT ACTIVATED) AVAI~|~Cellular Option (GPS Not Activated) available for all 33x / Advantage / Advantage-S / Advantage-HC / ChromaView / BroadView~|~91580957~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~957.18~|~957.18~|~1055.06~|~1152.93~|~957.18~|~957.18~|~957.18~|~957.18~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 17: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 17:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 18: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 18:",  e);
        }

        try {
            xsbData = "~|~~|~MONO MACHINES LLC~|~104479~|~5 Gallon, Cedar-Tone, Exterior Transparent Stain, VOC Less Than 350.~|~~|~~|~C4S6Z1ALKEP1~|~314120~|~332510C~|~false~|~DUCKBACK PRODUCTS~|~DB0019115-20~|~~|~1~|~EA~|~DUCKBACK PRODUCTS~|~DB001911520~|~EA~|~~|~~|~~|~~|~~|~5GAL CedarTon EXT Stain~|~~|~5GAL CedarTon EXT Stain~|~5 Gallon, Cedar-Tone, Exterior Transparent Stain, VOC Less Than 350.~|~6068624~|~1~|~8~|~0~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~156.36~|~151.79~|~173.75~|~195.7~|~151.79~|~172.46~|~176.43~|~186.91~|~11.86~|~0.0~|~0.0~|~0.0~|~0.0~|~HARDWARE ASSOCIATES, INC 47QSHA18D0027~|~GORILLA STATIONERS LLC 47QSEA20D006H~|~HARDWARE, INC. GS-21F-0104W~|~0.0~|~0.0~|~0.0~|~225.74~|~257.52~|~289.29~|~225.74~|~225.74~|~225.74~|~225.74~|~0.00~|~http://www.walmart.com~|~http://www.walmart.com~|~http://www.walmart.com~|~US~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~87.50~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 19: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 19:",  e);
        }

        try {
            xsbData = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Cellular Option (GPS Not Activated) available for all 33x / Advantage / Advantage-S / Advantage-HC / ChromaView / BroadView~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125310~|~EA~|~~|~~|~~|~~|~~|~CELLULAR OPTION (GPS NOT ACTIVATED) AVAI~|~~|~CELLULAR OPTION (GPS NOT ACTIVATED) AVAI~|~Cellular Option (GPS Not Activated) available for all 33x / Advantage / Advantage-S / Advantage-HC / ChromaView / BroadView~|~91580957~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~957.18~|~957.18~|~1055.06~|~1152.93~|~957.18~|~957.18~|~957.18~|~957.18~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~\n";
            log.info("Line 20: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 20:",  e);
        }

        try {
            xsbData = "qwer~|~|~|~ghhads~|~\n";
            log.info("Line 21: " + xsbDataParser.parseXsbDataToArray(xsbData).length);
        } catch (Exception e) {
            log.error("Line 21:",  e);
        }


    }


    @Test
    void parseInvalidXsbDataInvalidDelimiter() {
        String xsbData = "47QSMA21D08R6,,AMERICAN SIGNAL COMPANY,,Verizon VPN with ITS Cloud Manager per year subscription, available for all models,,,612764845,NEW,NEW,true,AMERICAN SIGNAL COMPANY,OPT30125380,,1,EA,AMERICAN SIGNAL,OPT30125380,EA,,,,,,VERIZON VPN WITH ITS CLOUD MANAGER PER Y,,VERIZON VPN WITH ITS CLOUD MANAGER PER Y,Verizon VPN with ITS Cloud Manager per year subscription, available for all models,91580958,1,1,1,,false,false,false,false,false,false,false,false,false,false,false,false,PP,,344.58,344.58,390.93,437.27,344.58,344.58,344.58,344.58,0.0,0.0,0.0,0.0,0.0,AMERICAN SIGNAL COMPANY 47QSMA21D08R6,AMERICAN SIGNAL COMPANY 47QSMA21D08R6,AMERICAN SIGNAL COMPANY 47QSMA21D08R6,0.0,0.0,0.0,,,,,,,,,,,,,0.00,Unknown,Unknown,gsa,gsa,gsa,9,false,,,,,,,,,,,,,,,,,100.00,,US,false,false,,,,,";        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(xsbData));
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(xsbData));
    }

    @Test
    void parseInvalidXsbDataNullString() {
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(null));
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToArray(""));

    }


    @Test
    void parseXsbDataToMap() {
        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice"};
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        String[] xsbData = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","",""};
        Map<String, String> expected = IntStream.range(0, expectedHeader.length)
                .boxed()
                .collect(Collectors.toMap(k -> expectedHeader[k], v -> xsbData[v]));
        assertEquals(expected, xsbDataParser.parseXsbDataToMap(xsbDataString));
    }

    @Test
    void parseExtendedXsbDataToMap_ExactNumberOfFieldsAsExtendedHeader() {
        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice", "mdfGroupId","extraHeader1","extraHeader2","extraHeader3"};
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~~|~1234567890~|~extraValue1~|~extraValue2~|~extraValue3";
        String[] xsbData = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","","", "1234567890", "extraValue1","extraValue2","extraValue3",};
        Map<String, String> expected = IntStream.range(0, expectedHeader.length)
                .boxed()
                .collect(Collectors.toMap(k -> expectedHeader[k], v -> xsbData[v]));
        assertEquals(expected, xsbDataParser.parseXsbDataToMap(xsbDataString));
    }

    @Test
    void parseExtendedXsbDataToMap_MoreFieldsThanExtendedHeader() {
        String[] expectedHeader = {"contractNumber","modificationNumber","vendorName","vendorPartNumber","vendorDescription","bpaNumber","solicitationNumber","dunsNumber","sin","sinInference","sinsMatch","manufacturerName","manufacturerPartNumber","quantityOfUnit","quantityPerUnit","unitOfIssue","standardizedManufacturerName","standardizedManufacturerPartNumber","standardizedUnitOfIssue","fsc","nsn","unspsc","globalPackagingIdentifier","standardizedGlobalPackagingIdentifier","productName","productType","standardizedProductName","standardizedProductDescription","uniqueItemIdentifier","standardizedPackageQuantity","hits","selfHits","abilityOneItem","bioPreferred","comprehensiveProcurementGuidelineCompliant","significantNewAlternativesPolicyApproved","federalEnergyManagementProgramEnergyEfficientItem","waterSense","saferChoice","energyStar","epeat","primeItem","epaPrimaryMetalsFree","lowVoc","ets","deliveryFob","uniqueItemIdentifierScore","finalPrice","lowPriceTarget","midPriceTarget","highPriceTarget","catalogMinPrice","catalogAvgPrice","catalogMedianPrice","catalogMaxPrice","catalogPriceStandardDeviation","transactionMinPrice","transactionAvgPrice","transactionMedianPrice","transactionMaxPrice","catalogMinPriceSupplier","catalogMedianPriceSupplier","catalogMaxPriceSupplier","catalogMinPriceDelta","catalogAvgPriceDelta","catalogMedianPriceDelta","commercialCatalogLowPriceTarget","commercialCatalogMidPriceTarget","commercialCatalogHighPriceTarget","commercialCatalogMinPrice","commercialCatalogAvgPrice","commercialCatalogMedianPrice","commercialCatalogMaxPrice","commercialCatalogPriceStandardDeviation","commercialCatalogMinPriceSupplier","commercialCatalogMedianPriceSupplier","commercialCatalogMaxPriceSupplier","countryOriginInference","demandWeightedIndexScore","rankCategory","salesLikelihood","catalogMinPriceSource","catalogMedianPriceSource","catalogMaxPriceSource","isAuthorizedVendor","isProhibited","prohibitionCondition","prohibitionReason","prohibitionComment","fedmallMinPrice","fedmallMedPrice","fedmallAvgPrice","fedmallMaxPrice","nasaSewpMinPrice","nasaSewpMedPrice","nasaSewpAvgPrice","nasaSewpMaxPrice","vppSupplyCategoryId","vppIndicator","itemIdentifier","systemOfRecord","annualDemandQuantity","standardizedSinPrevalence","userDefinedInput","countryOrigin","unattributedManufacturerPartNumber","isInvalid","invalidReason","tdrAvgPrice","tdrMaxPrice","tdrMedianPrice","tdrMinPrice", "mdfGroupId","extraHeader1","extraHeader2","extraHeader3"};
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~~|~1234567890~|~extraValue1~|~extraValue2~|~extraValue3~|~extraExtraValue1~|~extraExtraValue2";
        String[] xsbData = {"47QSMA21D08R6","","AMERICAN SIGNAL COMPANY","","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","","","612764845","NEW","NEW","true","AMERICAN SIGNAL COMPANY","OPT30125380","","1","EA","AMERICAN SIGNAL","OPT30125380","EA","","","","","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","","VERIZON VPN WITH ITS CLOUD MANAGER PER Y","Verizon VPN with ITS Cloud Manager per year subscription, available for all models","91580958","1","1","1","","false","false","false","false","false","false","false","false","false","false","false","false","PP","","344.58","344.58","390.93","437.27","344.58","344.58","344.58","344.58","0.0","0.0","0.0","0.0","0.0","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","AMERICAN SIGNAL COMPANY 47QSMA21D08R6","0.0","0.0","0.0","","","","","","","","","","","","","0.00","Unknown","Unknown","gsa","gsa","gsa","9","false","","","","","","","","","","","","","","","","","100.00","","US","false","false","","","","","", "1234567890", "extraValue1","extraValue2","extraValue3",};
        Map<String, String> expected = IntStream.range(0, expectedHeader.length)
                .boxed()
                .collect(Collectors.toMap(k -> expectedHeader[k], v -> xsbData[v]));
        assertEquals(expected, xsbDataParser.parseXsbDataToMap(xsbDataString));
    }

    @Test
    void parseExtendedXsbDataToMap_LessNumberOfFieldsAsExtendedHeader() {
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~~|~1234567890~|~extraValue1";
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbDataToMap(xsbDataString));
    }


    @Test
    void parseXsbDataInvalidTaaContryCodes() {
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbData(xsbDataString, "testFile.gsa", null, null));
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbData(xsbDataString, "testFile.gsa", new ArrayList<>(), null));

    }

    @Test
    void parseXsbDataInvalidSourceFileName() {
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbData(xsbDataString, null, taaCountryCodes, null));
        assertThrows(IllegalArgumentException.class, () -> xsbDataParser.parseXsbData(xsbDataString, "", taaCountryCodes, null));
    }

    @Test
    void parseXsbData() {
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        XsbData xsbData = xsbDataParser.parseXsbData(xsbDataString, "testFile.gsa", taaCountryCodes, null);
        assertEquals("47QSMA21D08R6", xsbData.getContractNumber());
        assertEquals("AMERICAN SIGNAL COMPANY", xsbData.getManufacturer());
        assertEquals("OPT30125380", xsbData.getPartNumber());
    }

    @Test
    void parseXsbDataWithGsaFeedDate() {
        LocalDate epoch = LocalDate.of(1970,1,1);
        String xsbDataString = "47QSMA21D08R6~|~~|~AMERICAN SIGNAL COMPANY~|~~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~~|~~|~612764845~|~NEW~|~NEW~|~true~|~AMERICAN SIGNAL COMPANY~|~OPT30125380~|~~|~1~|~EA~|~AMERICAN SIGNAL~|~OPT30125380~|~EA~|~~|~~|~~|~~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~~|~VERIZON VPN WITH ITS CLOUD MANAGER PER Y~|~Verizon VPN with ITS Cloud Manager per year subscription, available for all models~|~91580958~|~1~|~1~|~1~|~~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~false~|~PP~|~~|~344.58~|~344.58~|~390.93~|~437.27~|~344.58~|~344.58~|~344.58~|~344.58~|~0.0~|~0.0~|~0.0~|~0.0~|~0.0~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~AMERICAN SIGNAL COMPANY 47QSMA21D08R6~|~0.0~|~0.0~|~0.0~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~0.00~|~Unknown~|~Unknown~|~gsa~|~gsa~|~gsa~|~9~|~false~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~~|~100.00~|~~|~US~|~false~|~false~|~~|~~|~~|~~|~";
        XsbData xsbData = xsbDataParser.parseXsbData(xsbDataString, "testFile.gsa", taaCountryCodes, epoch);
        assertEquals("47QSMA21D08R6", xsbData.getContractNumber());
        assertEquals("AMERICAN SIGNAL COMPANY", xsbData.getManufacturer());
        assertEquals("OPT30125380", xsbData.getPartNumber());
        assertTrue(xsbData.getXsbData().asString().contains("\"gsaFeedDate\":\"1970-01-01\""));
    }
}